### PR TITLE
Add windows video

### LINKED ISSUE #26: Add camera adapter to Windows
Not sure what API can we use Windows yet. We need to do some research.

### PR DESCRIPTION
**Pull request by at-wat**
~Image size is fixed to 640x480.~
~Pixel format is fixed to RGB.~

~temporary branched from #83~ rebased
fix #26

### CODE REVIEW

**Comment by at-wat** [comment]
It works now, but enumerating device props seems not implemented yet in Wine. It works only on real Windows.

**Comment by at-wat** [comment]
Screen Shot 2020-02-24 at 14 19 27

**Comment by at-wat** [comment]
(Windows API is horrible to me)

**Comment by lherman-cs** [comment]
> (Windows API is horrible to me)

It does look horrible to me... I can't imagine interfacing with their APIs, as you did. lol

**Pull request merged**
