### PR TITLE
Fallback codecs

### LINKED ISSUE #107: Fallback codec
Select a fallback codec implementation if the first one was failed to initialize.
For example with the case of vaapi (higher priority) and vpx, try vaapi first, and if the environment doesn't have video acceleration hardware, use vpx.

It could be something like:
```go
codec.Register(webrtc.VP8, codec.VideoEncoderFallbacks(
  codec.VideoEncoderBuilder(vaapi.NewVP8Encoder),
  codec.VideoEncoderBuilder(vpx.NewVP8Encoder),
)
```

One problem is that user code doesn't have a way to know which implementation is used, so it's difficult to pass codec specific parameter if using fallback codec.
Adding `prop.Codec.ImplementationName string` and pass multiple `CodecParams` for each `ImplementationName` as `map[string]interface{}`?

### PR DESCRIPTION
**Pull request by at-wat**
Add a wrapper function to initialize codec and try next fallback codec if one fails.

### Reference issue
Fixes #107

### CODE REVIEW

**Comment by lherman-cs** [comment]
I feel like we need to redesign the codec package. This change definitely works. But, it feels that there's a disconnection between the library and the users.

1. We suddenly require them to register the codecs manually when they want to have a fallback

```
codec.Register(webrtc.VP8, codec.VideoEncoderFallbacks(
		// Use if hardware acceleration is available.
		codec.NamedVideoCodec{
			Name:  "vaapi",
			Codec: codec.VideoEncoderBuilder(vaapi.NewVP8Encoder),
		},
		// Software implementation should always available.
		codec.NamedVideoCodec{
			Name:  "vpx",
			Codec: codec.VideoEncoderBuilder(vpx.NewVP8Encoder),
		},
	))
```

2. Then, when they want to set the codec specific params, we require them to use the names from 1 (this also feels redundant).

```
		c.CodecParams = map[string]interface{}{
				"vaapi": vpxParam,
				"vpx":   vpxParam,
			}
```

3. Also, it's been really weird to me that when they import one of the codec packages, it suddenly registers with one or more payload types:

```
const (
	PCMU = "PCMU"
	PCMA = "PCMA"
	G722 = "G722"
	Opus = "OPUS"
	VP8  = "VP8"
	VP9  = "VP9"
	H264 = "H264"
)
```

I think we should instead let the users build the codecs by themselves, and we'll simply take them in `GetUserMedia`. What do you think?

**Comment by at-wat** [comment]
> I think we should instead let the users build the codecs by themselves, and we'll simply take them in `GetUserMedia`.

I'm not very sure what you suggested.
Do you mean removing `codec.Register()` from `init()` of each codec package and register required codecs by the user code?

**Comment by lherman-cs** [comment]
Sorry, it was definitely very vague. But, yes, you're right. I was thinking that we should remove `codec.Register()` from init and let the user to explicitly specify the codec in the `GetUserMedia`. 

I think it's really hard to get my idea across with just plain English ^^. So, I've created an experiment here, https://github.com/pion/mediadevices/commit/f6905fe81aba0f266b8170fadcd0cd8e954b86e4. It's definitely not a working example since I didn't implement everything, but I made changes that I think it's enough to express my idea. 

Following are the main changes:

1. We no longer require the user to specify the Codec Name, pass specific codec params, and import the codec to implicitly register the codec separately anymore. But, we rather have everything in `<specific codec>.Params`, e.g. `x264.Params`.
2. Specifying specific codec params becomes really easy and more straightforward since you just need to call `x264.NewParams()` and that's the only way you can specify the codec in `GetUserMedia`, so it's less error-prone. Also, we can avoid an empty interface (which is pretty awesome!)
3. Since now you're passing the builders, we can have it as an array and multiple builders with the same codec name will be fine. Essentially, we'll get a fallback method automatically.

**Comment by at-wat** [comment]
OK. https://github.com/pion/mediadevices/commit/f6905fe81aba0f266b8170fadcd0cd8e954b86e4 definitely makes sense to me.

**Pull request closed without merging**
