### PR TITLE
Update libopus static library to correct arch for darwin arm64

### PR DESCRIPTION
**Pull request by edaniels**
See https://github.com/pion/mediadevices/pull/368#issuecomment-1114623571

### CODE REVIEW

**Comment by Sean-Der** [comment]
@edaniels This is just removing, did you also intend to add the correct one?

thanks for opening this PR!

**Comment by edaniels** [comment]
@Sean-Der It's a modification! Curious that it's not an add and remove since it's binary.

**Comment by at-wat** [comment]
@edaniels Could you update
https://github.com/pion/mediadevices/blob/master/dockerfiles/darwin-arm64.cmake
https://github.com/pion/mediadevices/blob/master/dockerfiles/darwin-arm64.Dockerfile
to make it cross-compilable?
All other static libraries are built by the scripts in https://github.com/pion/mediadevices/tree/master/dockerfiles and it's very hard to be maintained in the future without cross-compilation.

**Comment by edaniels** [comment]
I did this via the make target so there's no changes to make. It looks like the wrong file was originally committed :)

**Comment by at-wat** [comment]
Is `pkg/codec/openh264/lib/libopenh264-darwin-arm64.a` incorrect as well?

**Comment by edaniels** [comment]
lookin good 8)
```
Non-fat file: ./pkg/codec/openh264/lib/libopenh264-darwin-arm64.a is architecture: arm64
Non-fat file: ./pkg/codec/openh264/lib/libopenh264-darwin-x64.a is architecture: x86_64
```

**Review by at-wat — APPROVED** [review]
LGTM:+1:

**Pull request merged**
