### PR TITLE
Fix linux camera label rule document

### PR DESCRIPTION
**Pull request by at-wat**
Fix https://github.com/pion/mediadevices/pull/311/files#r589148142

### CODE REVIEW

**Comment by edaniels** [comment]
good catch! I'd approve but I can't :P. LGTM

**Comment by at-wat** [comment]
Order of `video0` and `pci-0000:00:00.0-usb-0:0:0.0-video-index0` was also swapped.

**Comment by at-wat** [comment]
@edaniels could you take another look? (added test to ensure the label naming rule)

**Comment by edaniels** [comment]
Yep LGTM

**Pull request merged**
