### PR TITLE
Add opus-darwin-arm64 archive

### PR DESCRIPTION
**Pull request by qnkhuat**
#### Description
I used my own MacBook air m1 - macOS Montery beta to build this archive.

I tried to find a docker image so we can use your GitHub actions to build this.
But to the best of my knowledge, I haven't found any docker image for darwin-arm64 yet.

If possible please provide me with the base image, I'll add scripts to the make file.

#### Reference issue
Fixes #...

### CODE REVIEW

**Comment by at-wat** [comment]
I don't have any macOS environment... Could someone try it?

**Comment by zeeshanecosmob** [comment]
@qnkhuat I have one webrtc client which is using mediadevices & i want to create binding for ios/android, so i tried to generate the ios framework using gomobile using this fix but i'm getting error

$gomobile bind -target ios/arm64
gomobile: ios/arm64: go build -buildmode=c-archive -o /var/folders/_y/yg1pp_6d6nz_7v1dv0_33vxr0000gn/T/gomobile-work-3748573632/signaler-ios-arm64.a ./gobind failed: exit status 2
#github.com/pion/mediadevices/pkg/codec/opus
ld: in /Users/nidhi/go/src/mediadevices/pkg/codec/opus/lib/libopus-darwin-arm64.a(opus_encoder.c.o), building for iOS, but linking in object file (/Users/nidhi/go/src/mediadevices/pkg/codec/opus/lib/libopus-darwin-arm64.a(opus_encoder.c.o)) built for macOS,
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### This is the output of my `go env`

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/nidhi/Library/Caches/go-build"
GOENV="/Users/nidhi/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/nidhi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/nidhi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/nidhi/go/src/signaler/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_y/yg1pp_6d6nz_7v1dv0_33vxr0000gn/T/go-build3700368361=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by qnkhuat** [comment]
Hey @zeeshanecosmob ,
Sorry but I'm not familiar with building for mobile.

Are you sure you want to use this version bc this is built for MACOS arm64.

FYI this is my env
```GO111MODULE="on"
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/earther/Library/Caches/go-build"
GOENV="/Users/earther/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/earther/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/earther/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/homebrew/Cellar/go/1.16.6/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.16.6/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.6"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wy/f91k0xxj4qx9bx7j1vzls0740000gn/T/go-build2045875601=/tmp/go-build -gno-record-gcc-switches -fno-common"```

**Comment by zeeshanecosmob** [comment]
Yes @qnkhuat i suppose your mac is with m1 chip which is Arm based chipset. However Android/Ios both have arm based chipset. The only difference is floating point apis won't work with that.

**Comment by qnkhuat** [comment]
yea I think so. But isn't mobile supposed to have APIS for audios and videos where you can call directly?
Is it a hard requirement to use mediadevices ?

**Comment by zeeshanecosmob** [comment]
I know it's tough, i would required to make necessary changes in mediadevices for it to work. Would you mind sharing your configure script for build opus ?

**Comment by Meonardo** [comment]
> I don't have any macOS environment... Could someone try it?

I test on my M1 Mac Mini, works great, please approve this merge.

**Review by at-wat — COMMENTED** [review]
I'm wondering how it can be managed or updated in future.
At least, it would be better to add a note to README that version of `libopus-darwin-arm64.a` is not always synced with the archives for the other platforms.

**Review by at-wat — COMMENTED** [review]
> I tried to find a docker image so we can use your GitHub actions to build this.
> But to the best of my knowledge, I haven't found any docker image for darwin-arm64 yet.

@qnkhuat I'm trying to add cross-compile toolchain for darwin-arm64.
https://github.com/pion/mediadevices/compare/add-darwin-arm64-libs

Does https://github.com/pion/mediadevices/compare/add-darwin-arm64-libs#diff-4bb0755ff217d2c3eba60e980d276b13b74edc18f84165eac283378c9b7eda61 work?

**Comment by at-wat** [comment]
@qnkhuat added cross compiled arm64 darwin libraries.
Please try the master branch version when you have time!

**Pull request closed without merging**
