### PR TITLE
fix cLen in nocgo implementation of i444Toi420

### PR DESCRIPTION
**Pull request by neversi**
#### Description
Fix the length of buffer - cLen in `i444toI420()` in nocgo implementation

### CODE REVIEW

**Comment by neversi** [comment]
While optimizing copy of buffers in nocgo implementation, I have faced with this bug.

**Comment by neversi** [comment]
@edaniels could you please at this bug?

**Comment by edaniels** [comment]
Hi @neversi, can you write a test for this? Thanks!

**Comment by neversi** [comment]
@edaniels it can be reproduced by tests with CGO_ENABLED=0

Also, I have added mock scaler to be able to pass tests for nocgo implementation and fix the ratio for i422 converter.

Now all tests pass without errors

**Review by edaniels — APPROVED** [review]
LGTM

**Pull request merged**
