### PR TITLE
Expose device list update func

### PR DESCRIPTION
**Pull request by bazile-clyde**
#### Description
This PR exports the logic executed at startup to find and register cameras. This will allow us to discover cameras connected after our application has started.

### CODE REVIEW

**Comment by at-wat** [comment]
Do you think we can expose setup function in other drivers as well?
It would be better to have unified interface to update device list.

**Comment by bazile-clyde** [comment]
> Do you think we can expose setup function in other drivers as well?
> It would be better to have unified interface to update device list.

@at-wat Done! I skipped the `dummy.go` files in `audiotest` and `videotest`. I also skipped `vncdriver.go`  since there's no `func init`. Let me know if I should _not_ have skipped any of those.

**Comment by at-wat** [comment]
@bazile-clyde thanks!

I think it would be better in future to have another API that `mediadevices.MediaDevices` can automatically call them to update the device list.
For this, `Initialize` functions would be better to have godoc comments to mention this API is experimental.
What do you think?

**Comment by bazile-clyde** [comment]
> @bazile-clyde thanks!
> 
> I think it would be better in future to have another API that `mediadevices.MediaDevices` can automatically call them to update the device list. For this, `Initialize` functions would be better to have godoc comments to mention this API is experimental. What do you think?

That makes sense. I don't have strong opinions either way so I added it. Thanks for the quick turnaround btw!

**Review by at-wat — CHANGES_REQUESTED** [review]
Could you revert import block orders to keep them like
```go
import (
  "stdlib1"
  "stdlib2"

  "nonstdlib1"
  "nonstdlib2"
)
```

**Comment by bazile-clyde** [comment]
> Could you revert import block orders to keep them like
> 
> ```go
> import (
>   "stdlib1"
>   "stdlib2"
> 
>   "nonstdlib1"
>   "nonstdlib2"
> )
> ```

Done!

**Review by at-wat — APPROVED** [review]
LGTM!

**Pull request merged**
